name: Embedded CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      PRESET: Debug
      INSTALL_DIR: ${{ github.workspace }}/libraries/${{ env.PRESET }}
      BUILD_DIR: ${{ github.workspace }}/build/host/${{ env.PRESET }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure with CMake Preset
        run: cmake --preset $PRESET

      - name: Build
        run: cmake --build --preset $PRESET

      - name: Install
        run: cmake --install $BUILD_DIR --prefix $INSTALL_DIR