name: Embedded CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PRESET: Debug
    steps:
      - uses: actions/checkout@v4

      - name: Configure with CMake Preset
        run: |
          BUILD_DIR="${GITHUB_WORKSPACE}/build/host/${PRESET}"
          INSTALL_DIR="${GITHUB_WORKSPACE}/libraries/${PRESET}"
          cmake --preset "$PRESET" -B "$BUILD_DIR" -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR"

      - name: Build
        run: |
          BUILD_DIR="${GITHUB_WORKSPACE}/build/host/${PRESET}"
          cmake --build "$BUILD_DIR"

      - name: Install
        run: |
          BUILD_DIR="${GITHUB_WORKSPACE}/build/host/${PRESET}"
          INSTALL_DIR="${GITHUB_WORKSPACE}/libraries/${PRESET}"
          cmake --install "$BUILD_DIR" --prefix "$INSTALL_DIR"

      - name: Upload binaries as artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-libraries-${{ env.PRESET }}
          path: libraries/${{ env.PRESET }}

  # 2. Unit Testing
  UnitTesting:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run Unit Tests
        run: echo "TODO: Add Unit testing"
