name: Embedded CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
# 0. Code Static Analysis
  CodeStaticAnalysis:
    runs-on: ubuntu-latest
    steps:
      - name: Run Static Analysis
        run: echo "TODO"

# 0. Code Quality Analysis
  CodeQualityAnalysis:
    runs-on: ubuntu-latest
    steps:
      - name: Run Quality Analysis
        run: echo "TODO"

# 0. Firmware Low-Level Design
  FirmwareLowLevelDesign:
    runs-on: ubuntu-latest
    steps:
      - name: Run Doxygen
        run: echo "TODO"

        
  Build:
    runs-on: ubuntu-latest
    env:
      PRESET: Debug
    needs: CodeStaticAnalysis
    steps:
      - uses: actions/checkout@v4

      - name: Build Configuration 
        run: |
          BUILD_DIR="${GITHUB_WORKSPACE}/build/host/${PRESET}"
          INSTALL_DIR="${GITHUB_WORKSPACE}/libraries/${PRESET}"
          cmake --preset "$PRESET" -B "$BUILD_DIR" -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR"

      - name: Build
        run: |
          BUILD_DIR="${GITHUB_WORKSPACE}/build/host/${PRESET}"
          cmake --build "$BUILD_DIR"

      - name: Install
        run: |
          BUILD_DIR="${GITHUB_WORKSPACE}/build/host/${PRESET}"
          INSTALL_DIR="${GITHUB_WORKSPACE}/libraries/${PRESET}"
          cmake --install "$BUILD_DIR" --prefix "$INSTALL_DIR"

      - name: Upload binaries as artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-libraries-${{ env.PRESET }}
          path: libraries/${{ env.PRESET }}

  # 2. Unit Testing
  UnitTesting:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Run Unit Tests
        run: echo "TODO"

  # 3. Component Testing
  ComponentTesting:
    runs-on: ubuntu-latest
    needs: UnitTesting
    steps:
      - name: Run Component Tests
        run: echo "TODO"

  # 4. Component Integration Testing
  ComponentIntegrationTesting:
    runs-on: ubuntu-latest
    needs: ComponentTesting
    steps:
      - name: Run Component Integration Tests
        run: echo "TODO"
  
  # 5. System Integration Testing
  SystemIntegrationTesting:
    runs-on: ubuntu-latest
    needs: ComponentIntegrationTesting
    steps:
      - name: Run System Integration Tests
        run: echo "TODO"
 
  # 6. System Testing
  SystemTesting:
    runs-on:  ubuntu-latest
    needs: SystemIntegrationTesting
    steps:
      - name: Deploy and Run Tests
        run: echo "TODO"

  # 7. Acceptance Testing
  AcceptanceTesting:
    runs-on:  ubuntu-latest
    needs: SystemTesting
    steps:
      - name: Run Acceptance Scenarios
        run: echo "TODO"

  # 8. Documentation & Reporting
  Documentation:
    runs-on: ubuntu-latest
    needs: [UnitTesting, SystemTesting]
    steps:
      - name: Generate Documentation
        run: echo "TODO"

  # 9. Release & Distribution
  Release:
    runs-on: ubuntu-latest
    needs: [Build, Documentation]
    steps:
      - name: Generate Documentation
        run: echo "TODO"
