name: Embedded CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PRESET: Debug
      INSTALL_DIR: ${{ github.workspace }}/libraries/${{ env.PRESET }}
      BUILD_DIR: ${{ github.workspace }}/build/host/${{ env.PRESET }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure with CMake Preset
        run: cmake --preset ${{ env.PRESET }}

      - name: Build
        run: cmake --build --preset ${{ env.PRESET }}

      - name: Install
        run: cmake --install ${{ env.BUILD_DIR }} --prefix ${{ env.INSTALL_DIR }}
